config/routes.rb
Rails.application.routes.draw do
  get '/render_pdf', to: 'faturas#render_pdf'

  resources :taxas
  resources :moradores do
    collection do 
      get 'search'
      post 'datatable'
    end
  end

  resources :leituras do
    collection do
      get 'search'
      post 'datatable'
    end
  end

  resources :imoveis do
    collection do
      get 'search'
      post 'datatable'
    end

    member do
      get 'gerar_fatura'
    end

    resources :leituras, only: [:new, :create] do
      collection do
        get 'search'
        post 'datatable'
      end
    end

    resources :faturas, only: [] do
      collection do
        get 'search'
        post 'datatable'
        get 'gerar_fatura'
      end
    end
  end
  
  resources :audits, only: :show
  match '500', :to => 'errors#internal_server_error', :via => :all
  match '422', :to => 'errors#unacceptable', :via => :all
  match '404', :to => 'errors#not_found', :via => :all
  RESPOND_404.map { |r2|  get "/#{r2}", to: redirect("/404") } 
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/helpers/layout_helper.rb
module LayoutHelper
  # Used to achieve nested layouts without content_for. This helper relies on
  # Rails internals, so beware that it make break with future major versions
  # of Rails. Inspired by http://stackoverflow.com/a/18214036
  #
  # Usage: For example, suppose "child" layout extends "parent" layout.
  # Use <%= yield %> as you would with non-nested layouts, as usual. Then on
  # the very last line of layouts/child.html.erb, include this:
  #
  #     <% parent_layout "parent" %>
  #
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer) # rubocop:disable Rails/HelperInstanceVariable
    output = render(template: "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/views/layouts/partials/_footer.html.erb
<!--begin::Footer-->
<div id="kt_app_footer" class="app-footer">
    <!--begin::Footer container-->
    <div class="app-container container-fluid d-flex flex-column flex-md-row flex-center flex-md-stack py-3">
        <!--begin::Copyright-->
        <div class="text-dark order-2 order-md-1">
            <span class="text-muted fw-semibold me-1"><%= Time.zone.now.year %>&copy;</span>
            <a href="<%= root_path %>" target="_blank" class="text-gray-800 text-hover-primary"><%= Rails.application.class.module_parent_name %></a>
        </div>
        <!--end::Copyright-->
        <!--begin::Menu-->
        <ul class="menu menu-gray-600 menu-hover-primary fw-semibold order-1">
            <li class="menu-item">
                <a href="<%= root_path %>" target="_blank" class="menu-link px-2">About</a>
            </li>
            <li class="menu-item">
                <a href="<%= root_path %>" target="_blank" class="menu-link px-2">Support</a>
            </li>
            <li class="menu-item">
                <a href="<%= root_path %>" target="_blank" class="menu-link px-2">Purchase</a>
            </li>
        </ul>
        <!--end::Menu-->
    </div>
    <!--end::Footer container-->
</div>
<!--end::Footer-->

app/views/layouts/partials/_menu.html.erb
<div data-kt-menu-trigger="click" class='menu-item menu-accordion <%= active_collapse_menu?([["leituras", "*"]]) %>'>
  <!--begin:Menu link-->
  <span class="menu-link">
    <span class="menu-icon">
      <i class="ki-duotone ki-call fs-2">
        <span class="path1"></span>
        <span class="path2"></span>
        <span class="path3"></span>
        <span class="path4"></span>
        <span class="path5"></span>
        <span class="path6"></span>
        <span class="path7"></span>
        <span class="path8"></span>
      </i>
    </span>
    <span class="menu-title">Leitura</span>
    <span class="menu-arrow"></span>
  </span>
  <!--end:Menu link-->
  <!--begin:Menu sub-->
  <div class="menu-sub menu-sub-accordion">
    <!--begin:Menu item-->
    <div class="menu-item">
      <!--begin:Menu link-->
      <a class="menu-link" href='<%= leituras_path %>'>
        <span class="menu-bullet">
          <span class="bullet bullet-dot"></span>
        </span>
        <span class="menu-title">Lista</span>
      </a>
      <!--end:Menu link-->
    </div>
    <!--end:Menu item-->
    <!--begin:Menu item-->
    <div class="menu-item">
      <!--begin:Menu link-->
      <a class="menu-link" href='<%= new_leitura_path %>'>
        <span class="menu-bullet">
          <span class="bullet bullet-dot"></span>
        </span>
        <span class="menu-title">Novo(a)</span>
      </a>
      <!--end:Menu link-->
    </div>
    <!--end:Menu item-->
  </div>
  <!--end:Menu sub-->
</div>
<div data-kt-menu-trigger="click" class='menu-item menu-accordion <%= active_collapse_menu?([["imoveis", "*"]]) %>'>
  <!--begin:Menu link-->
  <span class="menu-link">
    <span class="menu-icon">
      <i class="ki-duotone ki-call fs-2">
        <span class="path1"></span>
        <span class="path2"></span>
        <span class="path3"></span>
        <span class="path4"></span>
        <span class="path5"></span>
        <span class="path6"></span>
        <span class="path7"></span>
        <span class="path8"></span>
      </i>
    </span>
    <span class="menu-title">Imoveis</span>
    <span class="menu-arrow"></span>
  </span>
  <!--end:Menu link-->
  <!--begin:Menu sub-->
  <div class="menu-sub menu-sub-accordion">
    <!--begin:Menu item-->
    <div class="menu-item">
      <!--begin:Menu link-->
      <a class="menu-link" href='<%= imoveis_path %>'>
        <span class="menu-bullet">
          <span class="bullet bullet-dot"></span>
        </span>
        <span class="menu-title">Lista</span>
      </a>
      <!--end:Menu link-->
    </div>
    <!--end:Menu item-->
    <!--begin:Menu item-->
    <div class="menu-item">
      <!--begin:Menu link-->
      <a class="menu-link" href='<%= new_imovel_path %>'>
        <span class="menu-bullet">
          <span class="bullet bullet-dot"></span>
        </span>
        <span class="menu-title">Novo(a)</span>
      </a>
      <!--end:Menu link-->
    </div>
    <!--end:Menu item-->
  </div>
  <!--end:Menu sub-->
</div>
<div data-kt-menu-trigger="click" class='menu-item menu-accordion <%= active_collapse_menu?([["moradores", "*"]]) %>'>
  <!--begin:Menu link-->
  <span class="menu-link">
    <span class="menu-icon">
      <i class="ki-duotone ki-call fs-2">
        <span class="path1"></span>
        <span class="path2"></span>
        <span class="path3"></span>
        <span class="path4"></span>
        <span class="path5"></span>
        <span class="path6"></span>
        <span class="path7"></span>
        <span class="path8"></span>
      </i>
    </span>
    <span class="menu-title">Moradores</span>
    <span class="menu-arrow"></span>
  </span>
  <!--end:Menu link-->
  <!--begin:Menu sub-->
  <div class="menu-sub menu-sub-accordion">
    <!--begin:Menu item-->
    <div class="menu-item">
      <!--begin:Menu link-->
      <a class="menu-link" href='<%= moradores_path %>'>
        <span class="menu-bullet">
          <span class="bullet bullet-dot"></span>
        </span>
        <span class="menu-title">Lista</span>
      </a>
      <!--end:Menu link-->
    </div>
    <!--end:Menu item-->
    <!--begin:Menu item-->
    <div class="menu-item">
      <!--begin:Menu link-->
      <a class="menu-link" href='<%= new_morador_path %>'>
        <span class="menu-bullet">
          <span class="bullet bullet-dot"></span>
        </span>
        <span class="menu-title">Novo(a)</span>
      </a>
      <!--end:Menu link-->
    </div>
    <!--end:Menu item-->
  </div>
  <!--end:Menu sub-->
</div>
<div data-kt-menu-trigger="click" class='menu-item menu-accordion <%= active_collapse_menu?([["taxas", "*"]]) %>'>
  <!--begin:Menu link-->
  <span class="menu-link">
    <span class="menu-icon">
      <i class="ki-duotone ki-call fs-2">
        <span class="path1"></span>
        <span class="path2"></span>
        <span class="path3"></span>
        <span class="path4"></span>
        <span class="path5"></span>
        <span class="path6"></span>
        <span class="path7"></span>
        <span class="path8"></span>
      </i>
    </span>
    <span class="menu-title">Taxas</span>
    <span class="menu-arrow"></span>
  </span>
  <!--end:Menu link-->
  <!--begin:Menu sub-->
  <div class="menu-sub menu-sub-accordion">
    <!--begin:Menu item-->
    <div class="menu-item">
      <!--begin:Menu link-->
      <a class="menu-link" href='<%= taxas_path %>'>
        <span class="menu-bullet">
          <span class="bullet bullet-dot"></span>
        </span>
        <span class="menu-title">Lista</span>
      </a>
      <!--end:Menu link-->
    </div>
    <!--end:Menu item-->
    <!--begin:Menu item-->
    <div class="menu-item">
      <!--begin:Menu link-->
      <a class="menu-link" href='<%= new_taxa_path %>'>
        <span class="menu-bullet">
          <span class="bullet bullet-dot"></span>
        </span>
        <span class="menu-title">Novo(a)</span>
      </a>
      <!--end:Menu link-->
    </div>
    <!--end:Menu item-->
  </div>
  <!--end:Menu sub-->
</div>

app/views/layouts/partials/_scrolltop.html.erb
<!--begin::Scrolltop-->
<div id="kt_scrolltop" class="scrolltop" data-kt-scrolltop="true">
    <i class="ki-duotone ki-arrow-up">
        <span class="path1"></span>
        <span class="path2"></span>
    </i>
</div>
<!--end::Scrolltop-->

app/views/layouts/partials/_sidebar.html.erb
<!--begin::Sidebar-->
<div id="kt_app_sidebar" class="app-sidebar flex-column" data-kt-drawer="true" data-kt-drawer-name="app-sidebar" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="225px" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_app_sidebar_mobile_toggle">
    <!--begin::Logo-->
    <div class="app-sidebar-logo px-6" id="kt_app_sidebar_logo">
        <!--begin::Logo image-->
        <%= link_to root_path do %>
            <%= image_tag "boleto_solar.png", class: "h-100px app-sidebar-logo-default theme-light-show" %>
            <%= image_tag "boleto_solar.png", class: "h-100px app-sidebar-logo-default theme-dark-show" %>
            <%= image_tag "boleto_small.png", class: "h-45px app-sidebar-logo-minimize" %>
        <% end %>
        <!--end::Logo image-->
        <!--begin::Sidebar toggle-->
                                <!--begin::Minimized sidebar setup:
                if (isset($_COOKIE["sidebar_minimize_state"]) && $_COOKIE["sidebar_minimize_state"] === "on") {
                    1. "src/js/layout/sidebar.js" adds "sidebar_minimize_state" cookie value to save the sidebar minimize state.
                    2. Set data-kt-app-sidebar-minimize="on" attribute for body tag.
                    3. Set data-kt-toggle-state="active" attribute to the toggle element with "kt_app_sidebar_toggle" id.
                    4. Add "active" class to to sidebar toggle element with "kt_app_sidebar_toggle" id.
                }
            -->
        <div id="kt_app_sidebar_toggle" class="app-sidebar-toggle btn btn-icon btn-shadow btn-sm btn-color-muted btn-active-color-primary body-bg h-30px w-30px position-absolute top-50 start-100 translate-middle rotate" data-kt-toggle="true" data-kt-toggle-state="active" data-kt-toggle-target="body" data-kt-toggle-name="app-sidebar-minimize">
            <i class="ki-duotone ki-double-left fs-2 rotate-1100">
                <span class="path1"></span>
                <span class="path2"></span>
            </i>
        </div>
        <!--end::Sidebar toggle-->
    </div>
    <!--end::Logo-->
    <!--begin::sidebar menu-->
    <div class="app-sidebar-menu overflow-hidden flex-column-fluid">
        <!--begin::Menu wrapper-->
        <div id="kt_app_sidebar_menu_wrapper" class="app-sidebar-wrapper hover-scroll-overlay-y my-5" data-kt-scroll="true" data-kt-scroll-activate="true" data-kt-scroll-height="auto" data-kt-scroll-dependencies="#kt_app_sidebar_logo, #kt_app_sidebar_footer" data-kt-scroll-wrappers="#kt_app_sidebar_menu" data-kt-scroll-offset="5px" data-kt-scroll-save-state="true">
            <!--begin::Menu-->
            <div class="menu menu-column menu-rounded menu-sub-indention px-3" id="#kt_app_sidebar_menu" data-kt-menu="true" data-kt-menu-expand="false">
                <!--begin:Menu item-->
                <div class="menu-item">
                    <!--begin:Menu link-->
                    <a class="menu-link <%= active_header_menu?([['home', 'index']]) %>" href="<%= root_path%>">
                        <span class="menu-icon">
                            <i class="ki-duotone ki-element-11 fs-2">
                                <span class="path1"></span>
                                <span class="path2"></span>
                                <span class="path3"></span>
                                <span class="path4"></span>
                            </i>
                        </span>
                        <span class="menu-title"><%= t('helpers.titles.home') %></span>
                    </a>
                    <!--end:Menu link-->
                </div>
                <!--end:Menu item-->
                 <!--begin:Menu item-->
                <%= render "layouts/partials/menu" %>
                <!--end:Menu item-->
            </div>
            <!--end::Menu-->
        </div>
        <!--end::Menu wrapper-->
    </div>
    <!--end::sidebar menu-->
    <!--begin::Footer-->
    <div class="app-sidebar-footer flex-column-auto pt-2 pb-6 px-6" id="kt_app_sidebar_footer">
        <a href="https://preview.keenthemes.com/html/metronic/docs" class="btn btn-flex flex-center btn-custom btn-primary overflow-hidden text-nowrap px-0 h-40px w-100" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss-="click" title="200+ in-house components and 3rd-party plugins">
            <span class="btn-label">Docs & Components</span>
            <i class="ki-duotone ki-document btn-icon fs-2 m-0">
                <span class="path1"></span>
                <span class="path2"></span>
            </i>
        </a>
    </div>
    <!--end::Footer-->
</div>
<!--end::Sidebar-->