config/routes.rb
Rails.application.routes.draw do
  get '/render_pdf', to: 'faturas#render_pdf'

  resources :taxas
  resources :moradores do
    collection do 
      get 'search'
      post 'datatable'
    end
  end

  resources :leituras do
    collection do
      get 'search'
      post 'datatable'
    end
  end

  resources :imoveis do
    collection do
      get 'search'
      post 'datatable'
    end

    member do
      get 'gerar_fatura'
    end

    resources :leituras, only: [:new, :create] do
      collection do
        get 'search'
        post 'datatable'
      end
    end

    resources :faturas, only: [] do
      collection do
        get 'search'
        post 'datatable'
        get 'gerar_fatura'
      end
    end
  end
  
  resources :audits, only: :show
  match '500', :to => 'errors#internal_server_error', :via => :all
  match '422', :to => 'errors#unacceptable', :via => :all
  match '404', :to => 'errors#not_found', :via => :all
  RESPOND_404.map { |r2|  get "/#{r2}", to: redirect("/404") } 
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/moradores_controller.rb
class MoradoresController < ApplicationController
    layout 'cruds'
    before_action :set_morador, only: [:show, :edit, :update, :destroy]

    # GET /moradores
    def index
        unless request.format.in?(['html', 'js'])
            @moradores = Morador.all
        end
        respond_to do |format|
            format.html
            format.json
            format.js
        end
    end

    # GET /moradores/1
    def show;end

    # GET /moradores/new
    def new
        @morador = Morador.new(morador_params)
    end

    # GET /moradores/1/edit
    def edit;end

    # POST /moradores
    def create
        @morador = Morador.new(morador_params)
        notice = 'Morador cadastrado(a) com sucesso.'
        respond_to do |format|
            if @morador.save
                remote = params.try(:[], :remote)
                location = [@morador]
                location.unshift(params[:controller].split("/")[0].to_sym) if params[:controller].split("/").length > 1
                format.html { redirect_to remote.blank? || remote == 'false' ? location : moradores_path, notice: notice}
                format.json { render :show, status: :created, location: @morador }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @morador.errors, status: :unprocessable_entity }
                format.turbo_stream { render :form_update, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /moradores/1
    def update
        notice = 'Morador alterado(a) com sucesso.'
        respond_to do |format|
            if @morador.update(morador_params)
                remote = params.try(:[], :remote)
                location = [@morador]
                location.unshift(params[:controller].split("/")[0].to_sym) if params[:controller].split("/").length > 1
                format.html { redirect_to remote.blank? || remote == 'false' ? location : moradores_path, notice: notice}
                format.json { render :show, status: :ok, location: location }
                format.js { flash[:notice] = notice}
            else
                format.html { render :edit, status: :unprocessable_entity  }
                format.json { render json: @morador.errors, status: :unprocessable_entity }
                format.turbo_stream { render :form_update, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /moradores/1
    def destroy
        @morador.destroy
        notice = 'Morador removido(a) com sucesso.'
        respond_to do |format|
            format.html { redirect_to params[:controller].split("/").map(&:to_sym), notice: notice }
            format.json { head :no_content }
            format.js { render partial: 'shared/errors', locals: {errors: @morador.errors} }
        end
    end

    def datatable
        respond_to do |format|
            format.json { render json: MoradoresDatatable.new(view_context) }
        end
    end

    def search
        respond_to do |format|
            format.json { render json: Morador.search(params[:search])  }
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_morador
            @morador = Morador.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def morador_params
            if params[:morador]
                    params.require(:morador).permit(:nome, :cpf, :deleted_at)
            end
        end


end
    

app/helpers/moradores_helper.rb
module MoradoresHelper
end

app/views/moradores/_datatable.html.erb
<%- model_class=Morador -%>

<% id ||=Time.now.to_i %>
<% remote ||=remote %>
<% datatable_url ||=datatable_moradores_url(remote: remote, format: 'json' ) %>
<% link_to_new ||=new_morador_url() %>


<!--begin::Wrapper-->
<div class="d-flex flex-stack mb-5">
    <!--begin::Search-->
    <div class="d-flex align-items-center position-relative my-1">
        <i class="ki-duotone ki-magnifier fs-1 position-absolute ms-6"><span class="path1"></span><span class="path2"></span></i>
        <input type="text" data-kt-docs-table-filter="search" class="form-control form-control-solid w-250px ps-15" placeholder="Pesquisar"/>
    </div>
    <!--end::Search-->

    <!--begin::Toolbar-->
    <div class="d-flex justify-content-end" data-kt-docs-table-toolbar="base">
        <!--begin::Add -->
        <%= link_to link_to_new, class: 'btn btn-primary', data: {bs: {toggle: "tooltip"} }, title: "Adicionar" do %>
            <i class="ki-duotone ki-plus fs-2"></i> Adicionar
        <% end %>
        <!--end::Add -->
    </div>
    <!--end::Toolbar-->
</div>
<!--end::Wrapper-->

<!--begin::Datatable-->
<div class="table-responsive">
    <table class="table align-middle table-row-dashed fs-6 gy-5" style="width:100%" id="table-moradores-<%= id %>">
        <thead>
            <tr>
                <th>#</th>
                                    
                        <th><%= model_class.human_attribute_name(:nome) %></th>
                    
                                    
                        <th><%= model_class.human_attribute_name(:cpf) %></th>
                    
                                    
                                <th><%= model_class.human_attribute_name(:created_at) %></th>
                <th><%= model_class.human_attribute_name(:updated_at) %></th>
                <th class="text-end min-w-100px"><%= t("helpers.actions") %></th>
            </tr>
        </thead>
        <tbody class="text-gray-600 fw-semibold"></tbody>
    </table>
</div>
<!--end::Datatable-->
<script type="text/javascript">
    "use strict";

    // Class definition
    var KTDatatablesServerSide = function () {
        // Shared variables
        var table;
        var dt;
        var filterPayment;

        // Private functions
        var initDatatable = function () {
            dt = $("#table-moradores-<%= id %>").DataTable({
                searchDelay: 1000,
                processing: true,
                serverSide: true,
                order: [[0, 'desc']],
                stateSave: true,
                language: {
                    url: 'https://cdn.datatables.net/plug-ins/1.11.5/i18n/pt-BR.json',
                },
                ajax: {
                    url: "<%= datatable_url %>",
                    type: "POST",
                    beforeSend: function(xhr) {
                        xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'));
                    }
                },
                columns: [
                    { "data": "index", "class": "col-md-1 coluna-index" },
                                            
                            { "data": "nome" },
                        	
                                            
                            { "data": "cpf" },
                        	
                                            	
                    	
                    { "data": "created_at" },
                    { "data": "updated_at" },
                    { "data": "opcoes", "orderable": false }
                ],
            });

            table = dt.$;
        }

        // Search Datatable --- official docs reference: https://datatables.net/reference/api/search()
        var handleSearchDatatable = function () {
            const filterSearch = document.querySelector('[data-kt-docs-table-filter="search"]');
            filterSearch.addEventListener('keyup', function (e) {
                dt.search(e.target.value).draw();
            });
        }



        // Public methods
        return {
            init: function () {
                initDatatable();
                handleSearchDatatable();
            }
        }
    }();

    // On document ready
    KTUtil.onDOMContentLoaded(function () {
        KTDatatablesServerSide.init();
    });
</script>

app/views/moradores/_form.html.erb
<% remote = false if remote == nil %>
<% id ||= Time.now.to_i %>


<%= form_with(model: morador, data: { turbo: remote  }, html: {class: 'form fv-plugins-bootstrap5 fv-plugins-framework'}) do |form| %>
    <%= hidden_field_tag :remote, remote %>
    <!-- Note: Para adicionar campo obrigatório é só adicionar a classe '.required' no label. -->
    <div class="card-body border-top p-9">
        <div class="row">
                            
                    
                        <div class="col-lg-6 col-md-4 col-sm-12 ">
                            <div class="form-group">
                                
                                    <%= form.label :nome, class: "form-label"  %>
                                    
                                        <%= form.text_field :nome, class: "form-control form-control-solid" %>
                                    
                                
                            </div>
                        </div>
                    
                
                            
                    
                        <div class="col-lg-6 col-md-4 col-sm-12 ">
                            <div class="form-group">
                                
                                    <%= form.label :cpf, class: "form-label"  %>
                                    
                                        <%= form.text_field :cpf, class: "form-control form-control-solid" %>
                                    
                                
                            </div>
                        </div>
                    
                
                            
                    
                
            
        </div>
    </div>
    <div class="card-footer d-flex justify-content-end py-6 px-9">
        <% unless remote %>
            <%= link_to "<i class='las la-arrow-left'></i> #{t("helpers.links.back")}".html_safe, moradores_path, :class=> "d-inline-block btn btn-secondary me-2" %>
        <% end %>
        <%= render "moradores/form_actions" %>
    </div>
<% end %>

app/views/moradores/_form_actions.html.erb
<%= button_tag :class => 'btn btn-primary', data: { disable_with: "Salvar <i class='las la-spinner'></i>" } do  %>
    <i class="las la-save"></i> <%= t 'helpers.links.save' %> 
<% end %>

app/views/moradores/_show.html.erb
<%- model_class = Morador -%>

<% resource ||= resource %>


<div class="row mb-7">
  
    <label class="col-lg-4 fw-semibold text-muted"><%= model_class.human_attribute_name(:nome) %> </label>
    <div class="col-lg-8">
      <span class="fw-bold fs-6 text-gray-800"><%= resource.try(:nome) %></span>
    </div>
  
</div>
<div class="row mb-7">
  
    <label class="col-lg-4 fw-semibold text-muted"><%= model_class.human_attribute_name(:cpf) %> </label>
    <div class="col-lg-8">
      <span class="fw-bold fs-6 text-gray-800"><%= resource.try(:cpf) %></span>
    </div>
  
</div>
<div class="row mb-7">
  
</div>

<div class="row mb-7 mt-3">
  <%= render partial: "audits/table", locals: {audits: resource.try(:own_and_associated_audits), show_collapse: 'show'} %>
</div>

app/views/moradores/_show_actions.html.erb
<%- model_class=Morador -%>

<% remote ||=remote %>

 <%= link_to edit_morador_path(morador), :class=> 'btn btn-warning me-2', :remote => remote do %>
    <i class="las la-edit"></i> Editar
<% end %>

<%= button_to morador_path(morador), :remote=> remote,
    :method => 'delete',
    :data => { :confirm => "Tem certeza que deseja remover?"},
    :class => 'btn btn-danger me-2' do %>
    <i class="las la-trash"></i> Remover
<% end %>

<%= link_to new_morador_path, class: "btn btn-primary me-2" do %>
    <i class="las la-plus"></i> Adicionar 
<% end %>

app/views/moradores/_table.html.erb
<%- model_class=Morador -%>





<!--begin::Accordion-->
<div class="accordion" id="kt_accordion_<% model_class.model_name %>">
  <div class="accordion-item">
    <h2 class="accordion-header" id="kt_accordion_<% model_class.model_name %>_header_1">
      <button class="accordion-button fs-4 fw-semibold" type="button" data-bs-toggle="collapse" data-bs-target="#kt_accordion_<% model_class.model_name %>_body_1" aria-expanded="true" aria-controls="kt_accordion_<% model_class.model_name %>_body_1">
        <%= model_class.model_name.human(count: 2).titleize %>
      </button>
    </h2>
    <div id="kt_accordion_<% model_class.model_name %>_body_1" class="accordion-collapse collapse <%= show_collapse %>" aria-labelledby="kt_accordion_<% model_class.model_name %>_header_1" data-bs-parent="#kt_accordion_<% model_class.model_name %>">
      <div class="accordion-body">
        <%= render partial: "moradores/datatable" , locals: {remote: remote} %>
      </div>
    </div>
  </div>
</div>
<!--end::Accordion-->

app/views/moradores/edit.html.erb
<%- model_class=Morador -%>
<% remote ||= remote || params.try(:[], :remote) %>

<% content_for :page_title, t('helpers.titles.edit', :model => model_class.model_name.human(count: 2).titleize) %>

<% content_for :breadcrumb do %>
    <li class="breadcrumb-item">
        <%= link_to model_class.model_name.human(count: 2).titleize, moradores_path, class: 'text-muted text-hover-primary' %>
    </li>
    <!--begin::Item-->
    <li class="breadcrumb-item">
        <span class="bullet bg-gray-400 w-5px h-2px"></span>
    </li>
    <!--end::Item-->
    <li class="breadcrumb-item active" aria-current="page"><%= t('helpers.links.edit') %></li>
<% end %>


<%= error_messages(@morador) %>

<% if remote == true || remote == 'true' %>
    <%= render "shared/remote_modal", 
        modal_class: "#{model_class.model_name.human.titleize}", 
        modal_title: t('helpers.titles.edit', 
        :model=> model_class.model_name.human.titleize) do %>
            <%= render "form" , morador: @morador, remote: true  %>
    <%  end %>
<% else %>
    <%= render "form" , morador: @morador %>
<% end %>

app/views/moradores/form_update.turbo_stream.erb
<%= turbo_stream.update "remote_modal_body" do %>
  <%= render "form" , morador: @morador, remote: true %>
<% end %>

app/views/moradores/index.html.erb
<%- model_class=Morador -%>


<% content_for :page_title, t('helpers.titles.list', :model => model_class.model_name.human(count: 2).titleize) %>

<% content_for :breadcrumb do %>
    <li class="breadcrumb-item">
        <%= link_to model_class.model_name.human(count: 2).titleize, moradores_path, class: 'text-muted text-hover-primary' %>
    </li>
    <!--begin::Item-->
    <li class="breadcrumb-item">
        <span class="bullet bg-gray-400 w-5px h-2px"></span>
    </li>
    <!--end::Item-->
    <li class="breadcrumb-item active" aria-current="page"><%= t('helpers.links.list') %></li>
<% end %>


<div class="card-body py-4">
    <%= render 'datatable' %>
</div>

app/views/moradores/new.html.erb
<%- model_class=Morador -%>
<% remote ||= remote || params.try(:[], :remote) %>

<% content_for :page_title, t('helpers.titles.new', :model => model_class.model_name.human(count: 2).titleize) %>

<% content_for :breadcrumb do %>
    <li class="breadcrumb-item">
        <%= link_to model_class.model_name.human(count: 2).titleize, moradores_path, class: 'text-muted text-hover-primary' %>
    </li>
    <!--begin::Item-->
    <li class="breadcrumb-item">
        <span class="bullet bg-gray-400 w-5px h-2px"></span>
    </li>
    <!--end::Item-->
    <li class="breadcrumb-item active" aria-current="page"><%= t('helpers.links.new') %></li>
<% end %>


<%= error_messages(@morador) %>

<% if remote == true || remote == 'true' %>
    <%= render "shared/remote_modal", 
        modal_class: "#{model_class.model_name.human.titleize}", 
        modal_title: t('helpers.titles.new', 
        :model=> model_class.model_name.human.titleize) do %>
            <%= render "form" , morador: @morador, remote: true  %>
    <%  end %>
<% else %>
    <%= render "form" , morador: @morador %>
<% end %>

app/views/moradores/show.html.erb
<%- model_class=Morador -%>
<% remote ||= remote || params.try(:[], :remote) %>


<% content_for :page_title, t('helpers.titles.show', :model => model_class.model_name.human(count: 2).titleize) %>

<% content_for :breadcrumb do %>
    <li class="breadcrumb-item">
        <%= link_to model_class.model_name.human(count: 2).titleize, moradores_path, class: 'text-muted text-hover-primary' %>
    </li>
    <!--begin::Item-->
    <li class="breadcrumb-item">
        <span class="bullet bg-gray-400 w-5px h-2px"></span>
    </li>
    <!--end::Item-->
    <li class="breadcrumb-item active" aria-current="page"><%= t('helpers.links.show') %></li>
<% end %>


<div class="card-body py-4">
  <% if remote == true || remote == 'true' %>
    <%= render "shared/remote_modal", 
        modal_class: "#{model_class.model_name.human.titleize}", 
        modal_title: t('helpers.titles.show', 
        :model=> model_class.model_name.human.titleize) do %>
          <%= render "show" , resource: @morador %>
    <%  end %>
  <% else %>
    <%= render "show" , resource: @morador %>
  <% end %>
</div>
<div class="card-footer d-flex justify-content-end py-6 px-9">
  <%= link_to moradores_path, :class=> "d-inline-block btn btn-secondary me-2" do  %>
    <i class="las la-arrow-left"></i> <%= t("helpers.links.back") %>
  <% end %>
  <%= render 'show_actions' , morador: @morador %>
</div>